### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by cossio**
CC @juliohm

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@cossio Why do you drop support for old versions of dependencies?

**Comment by cossio** [comment]
Because there was a breaking change in DataStructures, where you must use `first/last` instead of `front/back`.

**Comment by DilumAluthge** [comment]
Hmmmm. Is there a way to support both old and new versions of DataStructures at the same time?

**Comment by cossio** [comment]
I don't see how. Why would you want to do that?

**Comment by DilumAluthge** [comment]
Just wondering.

Whenever possible, it's good to keep compat for old versions of dependencies.

The fact that this PR drops support for so many versions of DataStructures means that users may start run into "unsatisfiable" resolver errors if they have other requirements that force them to use an older version of DataStructures.

If it truly isn't possible, don't worry about it.

**Comment by cossio** [comment]
I don't think it's possible here. There was a breaking change with DataStructures.

Right now I was getting "unsatisfiable" resolver errors due to the opposite reason: I have packages that want to use the most recent version of DataStructures and can't update because ValueHistories depends on the older versions of DataStructures.

**Comment by juliohm** [comment]
I understand the issue with dropping support to old versions of dependencies, but I think it is ok in this case. I will go ahead and merge it.

**Comment by cossio** [comment]
Thanks @juliohm ! Any chance we can tag a release?

**Pull request merged**
