### PR TITLE
name changes

### PR DESCRIPTION
**Pull request by tbreloff**

### CODE REVIEW

**Comment by Evizero** [comment]
we should deprecate the old types I think

**Comment by tbreloff** [comment]
What the best practice to deprecate?  I normally just break things without telling anyone.

**Comment by Evizero** [comment]
there is a macro for types, I'll look it up

**Comment by Evizero** [comment]
`Base.@deprecate_binding DynMultivalueHistory MVHistory`

**Comment by Evizero** [comment]
Thanks! I'm off for today. please feel free to merge once the tests pass

**Pull request merged**
