### PR TITLE
Add CompatHelper

### PR DESCRIPTION
**Pull request by ericphanson**
As suggested in https://github.com/JuliaML/ValueHistories.jl/pull/24#discussion_r431091523 (cc @DilumAluthge). Should help the compat issues.

### CODE REVIEW

**Review by DilumAluthge — APPROVED** [review]

**Comment by DilumAluthge** [comment]
@juliohm Can you merge this?

**Comment by ericphanson** [comment]
It would be great to either get this in or the dependencies otherwise bumped, since the compat is quite out of date!

**Comment by DilumAluthge** [comment]
Even if we bump the dependencies, we should still merge this PR to install CompatHelper. That way we get automatic dependency updates in the future.

**Comment by juliohm** [comment]
Thank you guys for the help.

**Pull request merged**
